name: neovimapi
version: 0.0.1
description: A sample command-line application.
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  msgpack:

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
